name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test_prettier:
    name: Test Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install Dependencies
        run: npm install
      - name: Run the prettier tests
        run: npm run prettier
  test_unit:
    name: Test Unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install Dependencies
        run: npm install
      - name: Run the tests
        run: npm run test:unit
